# Generated by Django 5.2 on 2025-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitat',
            options={'verbose_name': 'Habitat', 'verbose_name_plural': 'Habitats'},
        ),
        migrations.AddField(
            model_name='habitat',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Luas Area'),
        ),
        migrations.AddField(
            model_name='habitat',
            name='environment_status',
            field=models.TextField(default='Unknown', verbose_name='Status Lingkungan'),
        ),
        migrations.AddField(
            model_name='habitat',
            name='max_capacity',
            field=models.IntegerField(default=0, verbose_name='Kapasitas Maksimal'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='name',
            field=models.CharField(default='Unknown Habitat', max_length=100, verbose_name='Nama Habitat'),
        ),
    ]
