# Generated by Django 5.2 on 2025-04-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Individu')),
                ('species', models.CharField(max_length=100, verbose_name='Spesies')),
                ('origin', models.CharField(max_length=100, verbose_name='Asal Hewan')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('health_status', models.CharField(choices=[('Sehat', 'Sehat'), ('Sakit', 'Sakit'), ('Dalam Pemantauan', 'Dalam Pemantauan')], max_length=20, verbose_name='Status Kesehatan')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL Foto Satwa')),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitats.habitat', verbose_name='Habitat')),
            ],
            options={
                'verbose_name': 'Satwa',
                'verbose_name_plural': 'Data Satwa',
            },
        ),
    ]
