# Generated by Django 5.2 on 2025-04-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateField()),
                ('nama_dokter', models.CharField(max_length=100)),
                ('status_kesehatan', models.CharField(choices=[('Sehat', 'Sehat'), ('Sakit', 'Sakit')], max_length=10)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('pengobatan', models.TextField(blank=True, null=True)),
                ('catatan_tindak_lanjut', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
