# Generated by Django 5.2 on 2025-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan_selanjutnya', models.DateField()),
                ('frekuensi_pemeriksaan_bulanan', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
