# Generated by Django 5.2 on 2025-04-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jadwal', models.DateTimeField()),
                ('kapasitas_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atraksi',
            fields=[
                ('nama_atraksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attractions.fasilitas')),
                ('lokasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wahana',
            fields=[
                ('nama_wahana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attractions.fasilitas')),
                ('peraturan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Berpartisipasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('nama_fasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.fasilitas')),
            ],
            options={
                'unique_together': {('nama_fasilitas', 'id_hewan')},
            },
        ),
        migrations.CreateModel(
            name='JadwalPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_lh', models.CharField(max_length=50)),
                ('tgl_penugasan', models.DateTimeField()),
                ('nama_atraksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.atraksi')),
            ],
            options={
                'unique_together': {('username_lh', 'tgl_penugasan')},
            },
        ),
    ]
