# Generated by Django 5.2 on 2025-04-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pakan', models.CharField(max_length=100)),
                ('jumlah_pakan', models.PositiveIntegerField()),
                ('jadwal', models.DateTimeField()),
                ('status', models.CharField(choices=[('Menunggu Diberikan', 'Menunggu Diberikan'), ('Selesai Diberikan', 'Selesai Diberikan')], default='Menunggu Diberikan', max_length=20)),
                ('penjaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
