# Generated by Django 5.2 on 2025-04-29 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateField()),
                ('jumlah_tiket', models.IntegerField()),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('dibatalkan', 'Dibatalkan'), ('selesai', 'Selesai')], max_length=50)),
                ('nama_atraksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to='attractions.atraksi')),
                ('username_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username_p', 'nama_atraksi', 'tanggal_kunjungan')},
            },
        ),
    ]
